name: .NET

on:
  workflow_dispatch:
    
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      uses: igotinfected-ci/build-monogame@v2
      with:
        dotnet-version: "6.0.x"
        solution-path: '${{ github.workspace }}\ShaderPreview.sln'
        content-mgcb-path: '${{ github.workspace }}\Content'
        content-mgcb-platform: "DesktopGL"
        csproj-path: '${{ github.workspace }}\ShaderPreview.csproj'
        build-target: "Build"
        build-configuration: "Release"
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Build
        path: bin/Release/net6.0-windows
