name: .NET

on:
  workflow_dispatch:
    
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Install MGCB
      run: dotnet tool install -g dotnet-mgcb
      shell: pwsh
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Restore tools
      run: dotnet tool restore
      shell: pwsh
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Build
        path: bin/Release/net6.0-windows
